model:
  hidden_dim: 512
  num_layer: 4
  use_bn: False
  use_residual: False
  if_preprocess: True

train:
  device: 'cuda'
  lr: 0.001
  epochs: 500
  save_epoch_interval: 10
  dataset_path: './data/z_data/'
  lr_steps: 50
